# -- 코드를 입력하세요
# SELECT U.USER_ID, U.NICKNAME, 
# # B.PRICE
# (
#     SELECT WRITER_ID, SUM(PRICE)
#     FROM USED_GOODS_BOARD
#     GROUP BY WRITER_ID
# ) AS TEST


# FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
# # WHERE U.USER_ID = 'kwag98' and
# WHERE B.STATUS = 'DONE'
# # GROUP BY U.USER_ID


# SELECT 
#     U.USER_ID,
#     U.NICKNAME,
#     SUM(B.PRICE) AS TOTAL_PRICE
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
# WHERE B.STATUS = 'DONE'
# GROUP BY U.USER_ID, U.NICKNAME
# ORDER BY TOTAL_PRICE;

SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY B.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
